name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - run: npm run build
      - run: npm run test
      - run: npm run test:cov
      - name: Publish test coverage report
        uses: EndBug/add-and-commit@v4
        with:
          add: docs
          force: true
          message: Add generated docs
          branch: pages
        env:
          GITHUB_TOKEN: ${TOKEN}
